apiVersion: v1
kind: PersistentVolume
metadata:
  name: turbofan-models-pv
  labels:
    type: local
    app: turbofan-api
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/Users/hp/Downloads/mlops-turbofan-project/models
    type: Directory