apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbofan-api
spec:
  template:
    spec:
      containers:
      - name: turbofan-api
        $patch: replace  # <-- THIS IS THE KEY!
        env:
        - name: MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: turbofan-api-config
              key: MODEL_PATH
        - name: APP_ENV
          value: staging
        - name: LOG_LEVEL
          value: DEBUG