apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbofan-api
spec:
  template:
    spec:
      containers:
      - name: turbofan-api
        env:
        - name: APP_ENV
          value: staging
        - name: LOG_LEVEL
          value: DEBUG