apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: turbofan-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: turbofan-staging.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: turbofan-api-service
            port:
              number: 8000