apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: turbofan-staging

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: turbofan-api

# Set replicas
replicas:
  - name: turbofan-api
    count: 3

# Add labels here instead
labels:
  - pairs:
      app: turbofan-api
      managed-by: argocd